### ISSUE TITLE
Question - How to use

### ISSUE THREAD

**Issue by thim81** [seongwon-kang/postman-collection-editor#1]
Hi,

Based on your code I understood that this package modifies a postman collection by adding "tests" to the collection.

Could you add an example on how to use the CLI or with a code on how to modify a postman collection (and add the original postman collection as example).

I'm looking for something similar, but not sure how your project works.

**Comment by seongwon-kang** [comment]
@thim81 Sorry I'm not working on this now :(
it will great if there is a openapi spec -> postman collection generator..

https://github.com/OpenAPITools/openapi-generator

**Comment by thim81** [comment]
@seongwon-kang 

Could you share what you want to build? What is your idea/vision behind this tool.
Because I might want to contribute, because I think I'm trying to achieve a similar thing.

I expect:
- Have a working postman collection (manually created or generated) with all API endpoints, environments.
- Extend this postman collection with tests in a automatic manner, based on the API endpoints
- Save this extended collection
- Use the collection in automation via Newman
